### ISSUE TITLE
Spreadsheet version of data

### ISSUE THREAD

**Issue by yfreemark** [ChicagoCityscape/gis-data#1]
It would be useful to have all these entrances editable in a spreadsheet; we could them name them based on geographic location or street intersection, etc.

**Comment by stevevance** [comment]
Okay, this can easily be done using `ogr2ogr` and the following export script:

```
ogr2ogr -f CSV cta.csv PG:"host=localhost port='54323' dbname='cityscape' user='xxx' password='yyy'" -sql "select name,agency,line,st_force2d(geom_4326), ST_Y(geom_4326) as latitude, ST_X(geom_4326) as longitude from stations_entrances where agency = 'CTA'"
```

**Comment by stevevance** [comment]
uploaded, check out the README for the links to CSV files.
