### ISSUE TITLE
144 stations total

### ISSUE THREAD

**Issue by yfreemark** [ChicagoCityscape/gis-data#2]
A few clarifications:
-- there are 144 stations total on the CTA (when the two Loop stations are merged into Washington/Wabash)
-- 95th/Dan Ryan has three entrances identified
-- Wilson has four entrances identified

**Comment by stevevance** [comment]
Here's a great opportunity to learn how to fix the data yourself. 
1. Go to the [README file](https://github.com/ChicagoCityscape/tod-data/blob/master/README.md) and click the "Edit" button (looks like a pencil, right of the "Raw" button). 
2. The repo will be forked into your account and you'll get an editor. Make the changes. 
3. Submit the changes with a "Pull Request" (GitHub makes editing text files really easy and walks you through these steps).
